import { ArrowRight, ArrowUpRight, Check, ChevronRight, CircleCheck, Mail, MapPin, MessageCircle, Phone, Quote } from 'lucide-react';
import Header from './components/Header';
import ContactForm from './components/ContactForm';
import AssistantWidget from './components/AssistantWidget';
import wowDetailingLogo from './assets/wow-detailing-logo.jpg';
import { clients, services, solutions, testimonials } from './data/siteData';

const Linkedin = () => <span aria-hidden="true" style={{fontWeight:800,fontSize:13}}>in</span>;

const SectionHead = ({eyebrow,title,text}) => <div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>;

const ClientLogo = ({type}) => {
  if (type === 'clarity') return <div className="client-logo clarity-logo"><span>CLARITY</span><small>CONSULTING GROUP</small></div>;
  if (type === 'itech') return <div className="client-logo itech-logo"><span><i>i</i>TECH</span><small>SOFTWARE SOLUTIONS</small></div>;
  if (type === 'vymo') return <div className="client-logo vymo-logo"><i/><span>vymo</span></div>;
  return <div className="client-logo wow-logo"><img src={wowDetailingLogo} alt="WOW Detailing"/></div>;
};

export default function App() { return <>
  <Header/><main id="main">
    <section className="hero" id="top"><div className="orb orb-one"/><div className="orb orb-two"/><div className="container hero-grid"><div className="hero-copy"><div className="hero-kicker"><span/>Salesforce, shaped around your business</div><h1>Build a CRM your teams <em>love</em> to use.</h1><p>CloudInfy aligns people, process, and platform to create Salesforce solutions that are clear, scalable, and ready for what comes next.</p><div className="hero-actions"><a className="btn" href="#contact">Plan your Salesforce roadmap <ArrowRight size={18}/></a><a className="text-link" href="#services">Explore our services <ChevronRight size={17}/></a></div><div className="hero-proof"><div><strong>Business-led</strong><span>from discovery onward</span></div><div><strong>Built to evolve</strong><span>long after launch</span></div></div></div>
      <div className="hero-visual" aria-label="Revenue performance dashboard"><div className="dash-glow"/><div className="dash-card main-dash"><div className="dash-top"><div><small>Revenue intelligence</small><strong>Quarterly revenue forecast</strong></div><span className="live"><i/> On track</span></div><div className="chart"><div className="chart-label"><div><small>Forecasted revenue</small><strong className="revenue-total">$2.84M</strong></div><span>↑ 28.4% <small>vs last quarter</small></span></div><svg viewBox="0 0 420 165" role="img" aria-label="Revenue forecast trending upward from January through June"><defs><linearGradient id="revenue-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e54b4f" stopOpacity=".35"/><stop offset="1" stopColor="#e54b4f" stopOpacity="0"/></linearGradient><linearGradient id="revenue-line" x1="0" y1="0" x2="1" y2="0"><stop stopColor="#c92034"/><stop offset="1" stopColor="#f28a4b"/></linearGradient></defs><path className="chart-grid" d="M0 38H420M0 78H420M0 118H420"/><path d="M4 130 C38 126 48 108 78 113 S122 95 150 99 S195 65 227 76 S270 48 300 55 S350 21 416 25 L416 148 L4 148Z" fill="url(#revenue-area)"/><path d="M4 130 C38 126 48 108 78 113 S122 95 150 99 S195 65 227 76 S270 48 300 55 S350 21 416 25" fill="none" stroke="url(#revenue-line)" strokeWidth="5" strokeLinecap="round"/><circle cx="416" cy="25" r="7" fill="#fff" stroke="#f28a4b" strokeWidth="4"/><text x="4" y="163">JAN</text><text x="83" y="163">FEB</text><text x="162" y="163">MAR</text><text x="241" y="163">APR</text><text x="320" y="163">MAY</text><text x="392" y="163">JUN</text></svg></div><div className="metric-row"><div><small>Qualified pipeline</small><strong>$4.18M</strong></div><div><small>Forecast confidence</small><strong>91%</strong></div><div><small>Average deal size</small><strong>$48.6K</strong></div></div></div><div className="dash-card side-dash"><div className="status-top"><small>Automation health</small><span><i/> Live</span></div><div className="ring"><strong>92</strong><span>%</span></div><strong className="status-heading">Systems running smoothly</strong><span className="muted">1,284 actions completed today</span><div className="status-bar"><i/></div><div className="status-stats"><span><b>24</b> active flows</span><span><b>0</b> errors</span></div></div><div className="floating-pill"><CircleCheck/> Data synced <span>just now</span></div></div>
    </div><div className="hero-bottom"><div className="container"><span>Strategy</span><i/><span>Implementation</span><i/><span>Development</span><i/><span>Continuous improvement</span></div></div></section>

    <section className="section about" id="about"><div className="container split"><div><SectionHead eyebrow="About CloudInfy" title={<>Technology is only powerful when it makes work <em>simpler.</em></>} /><a className="text-link dark" href="#contact">Meet your Salesforce partner <ArrowUpRight size={17}/></a></div><div className="about-copy"><p className="lead">We help organizations build scalable Salesforce platforms that transform the way they sell, serve, and grow.</p><p>Our approach starts with listening. We learn the business problem, simplify the process, and then design the right technology around it—so every solution is useful today and maintainable tomorrow.</p><div className="principles"><div><strong>01</strong><span>Clarity before configuration</span></div><div><strong>02</strong><span>Outcomes over output</span></div><div><strong>03</strong><span>Partnership beyond launch</span></div></div></div></div></section>

    <section className="section services" id="services"><div className="container"><div className="services-intro"><SectionHead eyebrow="Services & solutions" title={<>Expertise that turns complexity into <em>momentum.</em></>} text="From a clear plan to an adopted platform, one senior team stays accountable throughout."/><a className="text-link dark" href="#contact">Talk to an expert <ArrowUpRight size={17}/></a></div><div className="service-marquee"><div className="service-track">{[...services,...services].map(({icon:Icon,title,text},i)=><article className="service-card" key={`${title}-${i}`} aria-hidden={i >= services.length}><span className="service-no">{String((i % services.length)+1).padStart(2,'0')}</span><Icon/><h3>{title}</h3><p>{text}</p><a href="#contact" aria-label={`Discuss ${title}`}>Discuss this service <ArrowUpRight size={16}/></a></article>)}</div></div></div></section>

    <section className="section solutions" id="solutions"><div className="container"><SectionHead eyebrow="Solutions in action" title={<>Built around the moments that <em>matter.</em></>} text="Representative solution patterns, ready to be replaced with approved CloudInfy case studies."/><div className="solution-marquee"><div className="solution-track">{[...solutions,...solutions].map(({icon:Icon,tag,title,text,impact},i)=><article className="solution-card" key={`${title}-${i}`} aria-hidden={i >= solutions.length}><div className="solution-icon"><Icon/></div><div><span>{tag}</span><h3>{title}</h3><p>{text}</p></div><div className="solution-impact"><small>Designed outcome</small><strong>{impact}</strong><span>0{(i % solutions.length)+1}</span></div></article>)}</div></div></div></section>

    <section className="section why"><div className="container why-grid"><div><SectionHead eyebrow="Why CloudInfy" title={<>Good partners leave you <em>stronger.</em></>}/><p>We pair practical engineering with thoughtful collaboration, giving your team the confidence to own what we build together.</p></div><div className="why-list">{['Business-first discovery','Scalable, secure architecture','Transparent communication','Quality-led delivery','Knowledge transfer and adoption','Responsive post-launch support'].map((x,i)=><div key={x}><span>{i+1}</span><h3>{x}</h3><Check/></div>)}</div></div></section>

    <section className="section clients" id="clients"><div className="container"><SectionHead eyebrow="Our clients" title={<>Trusted to solve what’s <em>next.</em></>} text="Organizations featured on CloudInfy’s original company website."/><div className="client-marquee"><div className="client-track">{[...clients,...clients].map((c,index)=><div className="client-card" key={`${c.name}-${index}`} aria-label={c.name} aria-hidden={index >= clients.length}><ClientLogo type={c.logo}/></div>)}</div></div></div></section>

    <section className="section testimonials"><div className="container"><div className="testimonial-intro"><SectionHead eyebrow="Partnership mindset" title={<>The experience matters as much as the <em>solution.</em></>}/><p className="placeholder-note">Sample testimonial copy—replace with approved customer quotes before launch.</p></div><div className="quote-grid">{testimonials.map((t,i)=><figure key={i}><Quote/><blockquote>“{t.quote}”</blockquote><figcaption><strong>{t.name}</strong><span>{t.role}</span></figcaption></figure>)}</div></div></section>

    <section className="section contact" id="contact"><div className="container contact-grid"><div className="contact-copy"><span className="eyebrow">Start a conversation</span><h2>Let’s make Salesforce work harder for your business.</h2><p>Tell us what you’re solving. We’ll bring a thoughtful point of view and a clear next step.</p><div className="contact-details"><a href="mailto:admin@cloudinfy.com"><Mail/>admin@cloudinfy.com</a><a href="tel:+918197299055"><Phone/>+91 81972 99055</a><a className="whatsapp-link" href="https://wa.me/918197299055" target="_blank" rel="noreferrer"><MessageCircle/> Chat on WhatsApp</a><address><MapPin/><span><strong>Singh Associates</strong><br/>1st Floor, Neori, Oyna<br/>Ranchi, Jharkhand 835217</span></address><div className="office-map"><iframe title="CloudInfy office location" src="https://www.google.com/maps?q=Singh%20Associates%2C%201st%20Floor%2C%20Neori%2C%20Oyna%2C%20Ranchi%2C%20Jharkhand%20835217&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a href="https://www.google.com/maps/search/?api=1&query=Singh%20Associates%2C%201st%20Floor%2C%20Neori%2C%20Oyna%2C%20Ranchi%2C%20Jharkhand%20835217" target="_blank" rel="noreferrer">Open in Google Maps <ArrowUpRight size={14}/></a></div></div></div><ContactForm/></div></section>
  </main>
  <footer><div className="container footer-grid"><div><a className="brand light" href="#top"><span className="brand-mark"><i/><i/><i/></span><span>Cloud<span>Infy</span></span></a><p>Business-focused Salesforce consulting, implementation, development, and support.</p><a className="social" href="https://www.linkedin.com" aria-label="LinkedIn placeholder"><Linkedin/></a></div><div><h3>Explore</h3><a href="#about">About</a><a href="#services">Services</a><a href="#solutions">Solutions</a><a href="#clients">Clients</a></div><div><h3>Services</h3><a href="#services">Consulting</a><a href="#services">Implementation</a><a href="#services">Development</a><a href="#services">Support</a></div><div><h3>Get in touch</h3><a href="mailto:admin@cloudinfy.com">admin@cloudinfy.com</a><a href="tel:+918197299055">+91 81972 99055</a><address>Singh Associates<br/>1st Floor, Neori, Oyna<br/>Ranchi, Jharkhand 835217</address><a href="#contact">Start a project <ArrowUpRight size={14}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} CloudInfy Business Solutions LTD.</span><div><a href="#">Privacy</a><a href="#">Terms</a></div></div></footer>
  <AssistantWidget/>
  </> }
